// Code generated by "stringer -type=_DXGI_OUTDUPL_POINTER_SHAPE_TYPE -output=dxgi_types_string.go"; DO NOT EDIT.

package d3d

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DXGI_OUTDUPL_POINTER_SHAPE_TYPE_MONOCHROME-1]
	_ = x[DXGI_OUTDUPL_POINTER_SHAPE_TYPE_COLOR-2]
	_ = x[DXGI_OUTDUPL_POINTER_SHAPE_TYPE_MASKED_COLOR-4]
}

const (
	__DXGI_OUTDUPL_POINTER_SHAPE_TYPE_name_0 = "DXGI_OUTDUPL_POINTER_SHAPE_TYPE_MONOCHROMEDXGI_OUTDUPL_POINTER_SHAPE_TYPE_COLOR"
	__DXGI_OUTDUPL_POINTER_SHAPE_TYPE_name_1 = "DXGI_OUTDUPL_POINTER_SHAPE_TYPE_MASKED_COLOR"
)

var (
	__DXGI_OUTDUPL_POINTER_SHAPE_TYPE_index_0 = [...]uint8{0, 42, 79}
)

func (i _DXGI_OUTDUPL_POINTER_SHAPE_TYPE) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return __DXGI_OUTDUPL_POINTER_SHAPE_TYPE_name_0[__DXGI_OUTDUPL_POINTER_SHAPE_TYPE_index_0[i]:__DXGI_OUTDUPL_POINTER_SHAPE_TYPE_index_0[i+1]]
	case i == 4:
		return __DXGI_OUTDUPL_POINTER_SHAPE_TYPE_name_1
	default:
		return "_DXGI_OUTDUPL_POINTER_SHAPE_TYPE(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
