// Code generated by "stringer -type=_DXGI_OUTDUPL_POINTER_SHAPE_TYPE -output=dxgi_types_string.go"; DO NOT EDIT.

package d3d

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DXGI_OUTDUPL_POINTER_SHAPE_TYPE_MONOCHROME-0]
	_ = x[DXGI_OUTDUPL_POINTER_SHAPE_TYPE_COLOR-1]
	_ = x[DXGI_OUTDUPL_POINTER_SHAPE_TYPE_MASKED_COLOR-2]
}

const __DXGI_OUTDUPL_POINTER_SHAPE_TYPE_name = "DXGI_OUTDUPL_POINTER_SHAPE_TYPE_MONOCHROMEDXGI_OUTDUPL_POINTER_SHAPE_TYPE_COLORDXGI_OUTDUPL_POINTER_SHAPE_TYPE_MASKED_COLOR"

var __DXGI_OUTDUPL_POINTER_SHAPE_TYPE_index = [...]uint8{0, 42, 79, 123}

func (i _DXGI_OUTDUPL_POINTER_SHAPE_TYPE) String() string {
	if i >= _DXGI_OUTDUPL_POINTER_SHAPE_TYPE(len(__DXGI_OUTDUPL_POINTER_SHAPE_TYPE_index)-1) {
		return "_DXGI_OUTDUPL_POINTER_SHAPE_TYPE(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return __DXGI_OUTDUPL_POINTER_SHAPE_TYPE_name[__DXGI_OUTDUPL_POINTER_SHAPE_TYPE_index[i]:__DXGI_OUTDUPL_POINTER_SHAPE_TYPE_index[i+1]]
}
